backend:
  name: welgeewebsite
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img/uploads
public_folder: img/uploads
collections:
  - name: "pages"
      label: "Page"
      delete: false # Prevent users from deleting documents in this collection
      editor:
        preview: true
      files:
        - file: "content/pages/news.md"
            label: "News Page"
            name: "news-page"
            fields:
              - {label: Template, name: template, widget: hidden, default: BlogIndex}
              - {label: Title, name: title, widget: string}
              - {label: Featured Image, name: featuredImage, widget: image}
              - {label: Date, name: date, widget: date}



